// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCky8SbsY_3JvpSGmkwUp7OuTe_ot7DpTI',
    appId: '1:812477867832:web:afe00c359d283a3b5fc3cd',
    messagingSenderId: '812477867832',
    projectId: 'prm393-d8d61',
    authDomain: 'prm393-d8d61.firebaseapp.com',
    storageBucket: 'prm393-d8d61.firebasestorage.app',
    measurementId: 'G-5P0XMPL352',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLA5W3JugCe_rzq0_z0gxMKCwN87Uo70w',
    appId: '1:812477867832:android:59db34589c1d45635fc3cd',
    messagingSenderId: '812477867832',
    projectId: 'prm393-d8d61',
    storageBucket: 'prm393-d8d61.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPyeKezjjk3HdrXgyQtKd50YliGnXqTNA',
    appId: '1:812477867832:ios:73b22aefe4a47d8b5fc3cd',
    messagingSenderId: '812477867832',
    projectId: 'prm393-d8d61',
    storageBucket: 'prm393-d8d61.firebasestorage.app',
    iosBundleId: 'com.example.myproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPyeKezjjk3HdrXgyQtKd50YliGnXqTNA',
    appId: '1:812477867832:ios:73b22aefe4a47d8b5fc3cd',
    messagingSenderId: '812477867832',
    projectId: 'prm393-d8d61',
    storageBucket: 'prm393-d8d61.firebasestorage.app',
    iosBundleId: 'com.example.myproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCky8SbsY_3JvpSGmkwUp7OuTe_ot7DpTI',
    appId: '1:812477867832:web:7b4036bc5d4860735fc3cd',
    messagingSenderId: '812477867832',
    projectId: 'prm393-d8d61',
    authDomain: 'prm393-d8d61.firebaseapp.com',
    storageBucket: 'prm393-d8d61.firebasestorage.app',
    measurementId: 'G-HKSFVM063J',
  );

}